# Include shared CI
include:
  - project: "epi2melabs/ci-templates"
    file: "wf-containers.yaml"

variables:
  NF_WORKFLOW_OPTS: "--fastq test_data/fastq/barcode01/HG002_small_test.fastq.gz"
  RELEASE_WORKFLOW: "no"
  CI_FLAVOUR: "new"

docker-run:
  # Define a 1D job matrix to inject a variable named MATRIX_NAME into
  #   the CI environment, we can use the value of MATRIX_NAME to determine
  #   which options to apply as part of the rules block below
  # NOTE There is a slightly cleaner way to define this matrix to include
  #   the variables, but it is broken when using long strings! See CW-756
  timeout: 4 hours  # Increase timeout to 2 hours
  parallel:
    matrix:
      - MATRIX_NAME: [
          "defaults",
          "skipmapping",
          "denovo",
        ]
  rules:
    # NOTE As we're overriding the rules block for the included docker-run
    #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
    #   being incorrectly scheduled for "detached merge request pipelines" etc.
    - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
      when: never
    - if: $MATRIX_NAME == "defaults"
      variables:
        # use default args defined above
        NF_IGNORE_PROCESSES: combinefastq,filter_telomeres2,reversecomplement,rmdup2,clusterAndExtractR1,clusterfilt2,combine_ref,coverage_filter,filter_cluster,mapping_name,mappingbam2,name_contigs,polish_genome,cluster
    - if: $MATRIX_NAME == "skipmapping"
      variables:
        NF_WORKFLOW_OPTS: "--fastq test_data/fastq/barcode01/HG002_small_test.fastq.gz --skipmapping"
        NF_IGNORE_PROCESSES: check_reference,combinefastq,cut_sites,filtering,filter_telomeres2,mappingbam,results,reversecomplement,rmdup2,telomere_sites,clusterAndExtractR1,clusterfilt2,combine_ref,coverage_filter,filter_cluster,mapping_name,mappingbam2,name_contigs,nm_filter,polish_genome,trim_restriction_site,cluster,trim_restriction_site_ref,coverage_filter2
    #- if: $MATRIX_NAME == "denovo"
    #  variables:
    #    NF_WORKFLOW_OPTS: "-executor.\\$$local.cpus 16 -executor.\\$$local.memory 32GB --fastq test_data/denovo_reads_test.fastq.gz --denovo"
    #    NF_IGNORE_PROCESSES: ""
